name: NES R.O.B. CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate_code: # job id
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run Tests In Container
        id: containerized_tests
        uses: ./.github/actions/run-tests-in-container
